=== iqb-specifications/acp-scale/acp-scale-base.schema.json
{
  "$id": "acp-scale-base@0.4",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Assessment Content Package: Base Scale",
  "description": "Specification for assessment content package scale of type 'base'.",
  "type": "object",
  "properties": {
    "id": {
      "description": "Identifier referred by other scales and assessment output.",
      "type": "string"
    },
    "name": {
      "$ref": "#/$defs/languageTaggedText"
    },
    "description": {
      "$ref": "#/$defs/languageTaggedText"
    },
    "method": {
      "description": "Way how to process the item values.",
      "type": "string",
      "enum": [
        "SCORE_SUM",
        "SCORE_RATIO",
        "SCORE_MEAN",
        "SCORE_MEDIAN",
        "WLE",
        "CODE_COUNT"
      ]
    },
    "methodParameters": {
      "description": "Depending on the method, different parameters may specify the processing.",
      "oneOf": [
        {
          "$ref": "#/$defs/methodParametersScoreRatio"
        },
        {
          "$ref": "#/$defs/methodParametersCodeCount"
        }
      ]
    },
    "items": {
      "description": "List of all items providing it's value to this scale",
      "type": "array",
      "items": {
        "$ref": "#/$defs/itemInScale"
      },
      "minItems": 1
    },
    "minItemNumber": {
      "description": "Minimum number of items in responses for this scale to be reported; set '0' for unlimited",
      "type": "number",
      "default": 0
    }
  },
  "required": [
    "id",
    "method",
    "items"
  ],
  "additionalProperties": false,
  "$defs": {
    "languageTaggedText": {
      "description": "Language tagged text",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "lang": {
            "description": "ISO-language code",
            "type": "string",
            "minLength": 1,
            "pattern": "^[a-z]{2}$"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "lang",
          "value"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "itemValueType": {
      "type": "string",
      "enum": [
        "FULL_CREDIT",
        "NO_CREDIT",
        "MISSING"
      ]
    },
    "methodParametersScoreRatio": {
      "description": "Parameters for the processing method SCORE_RATIO.",
      "type": "object",
      "properties": {
        "maxValue": {
          "description": "If methodParameters is not given, the number of items will be taken as maxValue",
          "type": "number"
        }
      },
      "required": [
        "maxValue"
      ],
      "additionalProperties": false
    },
    "methodParametersCodeCount": {
      "description": "Parameters for the processing method CODE_COUNT.",
      "type": "object",
      "properties": {
        "codeValue": {
          "description": "Value of code to be counted",
          "type": "number"
        }
      },
      "required": [
        "codeValue"
      ],
      "additionalProperties": false
    },
    "itemInScale": {
      "type": "object",
      "properties": {
        "id": {
          "description": "Identifier referring to unique identifier of item in unit list.",
          "type": "string"
        },
        "parameters": {
          "type": "array",
          "description": "List of item values relevant for processing",
          "items": {
            "type": "object",
            "properties": {
              "key": {
                "type": "string",
                "enum": [
                  "LOGIT_FULL_CREDIT",
                  "LOGIT_PARTIAL_CREDIT_1",
                  "LOGIT_PARTIAL_CREDIT_2",
                  "LOGIT_PARTIAL_CREDIT_3"
                ]
              },
              "value": {
                "type": "string"
              }
            },
            "required": [
              "key"
            ],
            "additionalProperties": false
          }
        },
        "weight": {
          "type": "number",
          "default": 1
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    }
  }
}

=== iqb-specifications/acp-scale/test/BASE_1.json
{
  "id": "base1.fcr",
  "name": [
    {
      "lang": "de",
      "value": "Lösungshäufigkeit"
    },
    {
      "lang": "en",
      "value": "full credit ratio"
    }
  ],
  "description": [
    {
      "lang": "de",
      "value": "Demo Skala vom Typ 'BASE' für Lösungshäufigkeit (Prozent)"
    },
    {
      "lang": "en",
      "value": "Demo scale BASE for full credit ratio"
    }
  ],
  "method": "SCORE_RATIO",
  "methodParameters": {
    "maxValue": 8
  },
  "items": [
    {
      "id": "JU7662804"
    },
    {
      "id": "JU7662801"
    },
    {
      "id": "JU7662802"
    },
    {
      "id": "JU7662803"
    }
  ]
}
